# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  domain_name: example.com
  secret_key_base: 42ef33fcabd8c284f725a3d9df273c865bacc7e250baa5182801103cf68ef69629d78fb855911d844500ff991f0475f0c24dc7d041b777c648054bc26501e47d

test:
  secret_key_base: c3d06a4270d6798c38d975ba1434716f7e4df55d27e531b04e019bb22409ff005b17fece41879e537edf4d326658346e6bf6245bf388b7e43c0a88a04972fdcc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
